### ISSUE TITLE
https://www.humdrum.org/rep/harm/ error in description of root alteration

### ISSUE THREAD

**Issue by musicnerd** [humdrum-tools/humdrum-documentation#17]
Hey guys. I thought it would be easier to post an issue rather than do a whole pull/edit/push for one small thing. I noticed the following today, which I believe is incorrect on this page: https://www.humdrum.org/rep/harm/

"For example, in the key of C minor, a minor chord having E-natural as a root would be encoded as iii."

This contradicts the earlier text which states that RNs follow the harmonic minor, but that roots are adjusted with - or #. So by this logic, iii should represent a minor chord built on Eb in the key of C minor. A minor chord built on E(nat) ought to be #iii .

**Comment by craigsapp** [comment]
Yes &mdash; I have fixed the documentation with this commit: 
https://github.com/humdrum-tools/humdrum-documentation/commit/c1be69333ae7e74a9478801e7800ae8129bbb08d

(You should be able to fix it directly as well, or I can add if to the repo if not).

I need to fix it again, because in the backup of the original documentation:

https://www.humdrum.org/Humdrum/representations/harm.rep.html

<img width="1092" alt="Screen Shot 2022-02-24 at 9 02 38 PM" src="https://user-images.githubusercontent.com/3487289/155656898-0fa5fa68-9fbd-43ad-b74d-02a3d9c49dc0.png">

There is a `#` in front of the `iii`.  This `#` must have been stripped out when converting the HTML to markdown.  The original text content of the documentation was in Troff, but that was lost (about 2005?) in a server upgrade.  I have been working with Dan to clean up the automatic conversion, but we have probably not done much in the representations section of the documentation (mostly just the user guide and not the command reference yet as well).

**Comment by craigsapp** [comment]
Fixed with commit https://github.com/humdrum-tools/humdrum-documentation/commit/cc06a57bd151bec04c921be106efa24a7e5030de
