### ISSUE TITLE
Voice changing staffs

### ISSUE THREAD

**Issue by Daniel63656** [humdrum-tools/humdrum-documentation#21]
Hey I couldn't find this information anywhere in the docs. Is it possible for voices (musical parts) to change staffs mid measure like commonly found in grand staff notation for piano?

**Comment by craigsapp** [comment]
Yes, although it is not part of the original documentation, so that is why it is hard to find...

Here is an example method used to display graphic music in Verovio Humdrum Viewer:

<img width="1286" alt="Screenshot 2024-05-08 at 4 31 55 AM" src="https://github.com/humdrum-tools/humdrum-documentation/assets/3487289/6d619cf1-5c29-40e4-b784-8896adc19e1d">

[[View in VHV](https://verovio.humdrum.org?t=KiprZXJuCSoqa2VybgoqcGFydDEJKnBhcnQxCipzdGFmZjIJKnN0YWZmMQoqY2xlZkY0CSpjbGVmRzIKKk00LzQJKk00LzQKPTEJPTEKKgkqXgoxQwkxY2MJOGUvTAouCS4JOGQvCi4JLgk4Yy8KLgkuCThCPFxKCi4JLgk4QTxMCi4JLgk4RzwKLgkuCThGPAouCS4JOEU8SgoqCSp2CSp2Cj0yfHwJPTJ8fAoqXgkqCjhFTAkxQwkxY2MKOEYJLgkuCjhHCS4JLgo4QUoJLgkuCjhCTC8JLgkuCjhjLwkuCS4KOGQ+XAkuCS4KOGU+XEoJLgkuCioJKnYJKnYKPT0JPT0KKi0JKi0KISEhUkRGKiprZXJuOiA+ID0gYWJvdmUKISEhUkRGKiprZXJuOiA8ID0gYmVsb3cK)]

When crossing staves, it is best to specify the stem directions (`\` and `/`) for the cross-staff beam (although not all are necessary for the renderer to figure this out). Once the voice is completely on the other staff, the renderer usually correctly guesses the stem directions (unless you want to cross the wandering voice to the other side of the voice(s) on the other staff).

The first measure demonstrates how a voice attached to the top staff can move to the bottom staff, and the second measure demonstrates the opposite case.

The method used is to define the meaning of the user signifiers `<` and `>`.  These must be placed immediately after the pitch and accidental.

```tsv
**kern	**kern
*part1	*part1
*staff2	*staff1
*clefF4	*clefG2
*M4/4	*M4/4
=1	=1
*	*^
1C	1cc	8e/L
.	.	8d/
.	.	8c/
.	.	8B<\J
.	.	8A<L
.	.	8G<
.	.	8F<
.	.	8E<J
*	*v	*v
=2||	=2||
*^	*
8EL	1C	1cc
8F	.	.
8G	.	.
8AJ	.	.
8BL/	.	.
8c/	.	.
8d>\	.	.
8e>\J	.	.
*	*v	*v
==	==
*-	*-
!!!RDF**kern: > = above
!!!RDF**kern: < = below
```

For real music, here is an example in Beethoven sonata no. 30, mvt. 1 starting at measure 88:

https://verovio.humdrum.org/?file=beethoven/sonatas/sonata30-1.krn

The reason why it must immediately follow the pitch/accidental is that it can be used for placements of articulations above and below the notes:

<img width="673" alt="Screenshot 2024-05-08 at 4 44 42 AM" src="https://github.com/humdrum-tools/humdrum-documentation/assets/3487289/24c11ed0-d14d-412d-bc0c-4c3386f3a62c">

[[View in VHV](https://verovio.humdrum.org?t=KiprZXJuCjRmJwo0Zic+CjRmXgo0Zl4+Cj0KKi0KISEhUkRGKiprZXJuOiA+ID0gYWJvdmUK)]

Here, the `>` marker is immediately after the articulation, which moves it above the notes.

If it is given after a beam start (`L`), then it will force the beamed group of notes up or down:

<img width="716" alt="Screenshot 2024-05-08 at 4 48 04 AM" src="https://github.com/humdrum-tools/humdrum-documentation/assets/3487289/0f823e45-a333-42df-a3eb-c5b098ba5602">

[[View in VHV](https://verovio.humdrum.org?t=KiprZXJuCjhiTAo4Ygo4Ygo4YkoKOGJMPgo4Ygo4Ygo4YkoKPQoqLQohISFSREYqKmtlcm46ID4gPSBhYm92ZQo=)]

In this case it is shorthand for giving stem directions on notes:

<img width="756" alt="Screenshot 2024-05-08 at 4 48 58 AM" src="https://github.com/humdrum-tools/humdrum-documentation/assets/3487289/5a08a4cb-17f0-4ca5-8c9f-17225931ad23">

[[View in VHV](https://verovio.humdrum.org?t=KiprZXJuCjhiTAo4Ygo4Ygo4YkoKOGIvTAo4Yi8KOGIvCjhiL0oKPQoqLQo=)]

(Although just a stem direction on the first note is sufficient to control the beamed-groups stem directions).
