### ISSUE TITLE
Handling of "forwards"

### ISSUE THREAD

**Issue by Daniel63656** [humdrum-tools/humdrum-documentation#22]
How are voices with "gaps" represented in kern? I attached an example. 
Would one have to split and join a new voice each time this happens? Consider that, while in the example, the gap in the green voice stretches across the barline, these gaps could totally appear within a measure. In MusicXML this is fixed using the <forward> element. Couldn't find how this is handled in the docs.

**Comment by craigsapp** [comment]
I don't see an attachment, but I can guess at what you are thinking of:

<img width="962" alt="Screenshot 2024-08-30 at 6 49 45 AM" src="https://github.com/user-attachments/assets/83f0c819-3ce5-41cd-b948-9dc2e70b802d">

[[View in VHV](https://verovio.humdrum.org?t=KiprZXJuCipNNC80Cj0xCjRjCjRkCjRlCjRmCj0KKl4KNGcJNGUKNGEJNHJ5eQo0Ygk0ZAo0Y2MvCTRyeXkKPQk9CjRyeXkJNGNcCjhyeXkJMmQKNGVlLwkuCjhnZy8JLgoqdgkqdgo9CiotCg==)]

Instead of splitting and merging every time, to voices are continued with invisible rests, `yy` means interpreted, or invisible in effect.

You can also use `**recip` durations without any pitch or rest (but I like to label them more explicitly with `ryy`):

<img width="892" alt="Screenshot 2024-08-30 at 6 54 57 AM" src="https://github.com/user-attachments/assets/08fd59cc-35f1-4496-898b-992301462dc9">

[[View in VHV](https://verovio.humdrum.org?t=KiprZXJuCipNNC80Cj0xCjRjCjRkCjRlCjRmCj0KKl4KNGcJNGUKNGEJNAo0Ygk0ZAo0Y2MvCTQKPQk9CjQJNGNcCjgJMmQKNGVlLwkuCjhnZy8JLgoqdgkqdgo9CiotCg==)]

**Comment by Daniel63656** [comment]
Sorry I forgot but your example is better anyway.
![voices](https://github.com/user-attachments/assets/1453a630-33cb-4f93-b92f-964f0f5398ce)

Ok so this is essentially the same solution as the concept of a forward in MusicXML then
Thank you
